### ISSUE TITLE
Suggestion for edit to step 2 in setting up the workshop environment with conda

### ISSUE THREAD

**Issue by LMCG8** [carpentries-incubator/geospatial-python#111]
Hi there! I suggest that in the set up, under 'Setting up the workshop environment with conda', step 2's bash command be modified to one line without the backslash breaks. As it is, it can't be pasted and function correctly for PC users. 

original:
`conda create -n geospatial -c conda-forge -y` \
   `jupyterlab numpy matplotlib` \
  `xarray rasterio geopandas rioxarray earthpy descartes xarray-spatial pystac-client python-graphviz`

suggested update:
`conda create -n geospatial -c conda-forge -y jupyterlab numpy matplotlib xarray rasterio geopandas rioxarray earthpy descartes xarray-spatial pystac-client python-graphviz`

**Comment by rbavery** [comment]
Sounds good. can you make a Pr for this @LMCG8 ?

**Comment by rbavery** [comment]
This actually works for me on a PC. I'm pasting into my WSL terminal and it pastes correctly. I also tried with GitBash, see below. I realize it may look different for you on GitBash, what issue occurs? This might have been fixed with the recent lesson update in #110 

![conda](https://user-images.githubusercontent.com/22258697/196303472-9a3b7ad6-5b1c-4c6d-8958-2594b46ae019.PNG)
