### ISSUE TITLE
Improving Episode 5

### ISSUE THREAD

**Issue by vinisalazar** [carpentries-incubator/geospatial-python#47]
Hi, I have a couple of concerns for Episode 5:

* The first is in the `surface_HARV = rioxarray.open_rasterio("data/NEON-DS-Airborne-Remote-Sensing/HARV/DSM/HARV_dsmCrop.tif")` line. In the setup page, instructions state that the downloaded data should be moved inside the `geospatial-python` directory and then unzipped. This may cause FileNotFoundErrors, that are easy to solve, but could be avoided. I propose that either the `"data/"` string is removed from the `open_rasterio` function OR that the setup instructions state that a `data` directory needs to be created (I believe the former is easier). 
* This is related to #22: There is a "Plotting Tip" callout in Episode 05, but plotting with Matplotlib is only introduced in Episode 06. I believe that this Plotting Tip could be somewhere else in the lesson, and there could a more detailed section on how to customize plots with Matplotlib. Since #19 also discusses merging Episode 06, I don't know what would be the best way to tackle this.

I hope this is helpful for the discussion.

Best wishes,
V

**Comment by rbavery** [comment]
Definitely helpful, thanks @vinisalazar !

On the first point, when I unzip the folder on my Mac, the result is a data folder that contains the sub directories for each dataset. Is this not the case on your end? I can test this out on windows tomorrow, I thought that when the .zip is extracted, the result is always a folder called "data" that contains the subdirectories, so a data folder wouldn't need to be created.

On the second point, I agree we could improve the introduction of plotting with matplotlib + xarray's 'plot' methods, it'd probably be good to discuss briefly how they complement each other. 

First, I think it'd be best to remove Episode 6's use of the `reproject` function following #19. The first part of Episode 7 could become episode 6, focusing on using `reproject_match` to align different rasters. We could also keep the challenge on masking no data values prior to plotting since this doesn't use matplotlib.

The second part of Episode 7 currently focuses on running a calculation to get a Canopy Height Model and making a pretty plot. This could formally introduce customizing plots with matplotlib and earthpy, since that sets up the later episodes. 

I think it's ok to still keep the code that use `plt.title` in the episodes before this one, just to get folks gradually familiar with it before it is formally introduced, also because this lesson assumes that people have taken a novice python lesson that teaches matplotlib and exposes folks to methods and attributes. But I'm also not opposed to removing these until after the section on customizing plots.

**Comment by vinisalazar** [comment]
Hi @rbavery, 

> Is this not the case on your end?

I tried it again and that is indeed the case. Sorry for that.

>  this lesson assumes that people have taken a novice python lesson that teaches matplotlib and exposes folks to methods and attributes. 
> On the second point, I agree we could improve the introduction of plotting with matplotlib + xarray's 'plot' methods, it'd probably be good to discuss briefly how they complement each other.

That is a fair point that people should be familiar with Matplotlib. Thinking about it now, expanding the "Plotting Tip" block in Episode 05 could be a way of having the Matplotlib introduction. And then on Episode 7, learners will already be more familiar.

**Comment by vinisalazar** [comment]
I will submit a PR with a tentative approach.

**Comment by rbavery** [comment]
Great, that sounds good to me. If you don't get to it, I'll work on the episode 6 refactor to focus on reproject_match and dealing with no data values with masking. Thanks a bunch for your comments and help, much appreciated!

**Comment by rbavery** [comment]
it's addressed see https://github.com/carpentries-incubator/geospatial-python/issues/19
